### ISSUE TITLE
Add usage example

### ISSUE THREAD

**Issue by alexbaumgertner** [krasimir/anatomia#1]
Could you add some this tool usage examples?

Thanks!

**Comment by krasimir** [comment]
Oh sorry, it's still not ready. My idea is to track the script flow and report it to the developer. Unfortunately it's still not ready.

**Comment by alexbaumgertner** [comment]
Thank you for quick answer!
You could check http://rileyjshaw.com/challenger/ for ideas, it's pretty nice lib for code testing.
Looks like this:

``` js
// indicates that the student must include an if statement within a while
// statement, but must not include a for statement within a while statement.
var challenge = {
  // ...
  nestedRules: {
    WhileStatement: {
      IfStatement: {
        required: true
      },
      ForStatement: {
        required: false
      }
    }
  }
};
```

**Comment by krasimir** [comment]
:+1:
